import { afterEach, expect, test } from "bun:test"
import { createReadStream, existsSync } from "node:fs"
import { mkdir, mkdtemp, rm } from "node:fs/promises"
import os from "node:os"
import path from "node:path"
import { Database } from "@opencode-ai/core/database/database"
import { V1Migration } from "@opencode-ai/core/database/v1-migration"
import { Global } from "@opencode-ai/util/global"
import { Effect } from "effect"
import { copyV1Store, inspectV1Source } from "../src/import-v1-session"

type SessionRow = {
  readonly id: string
  readonly summary_diffs: string | null
}

type SourceMessage = {
  readonly id: string
  readonly data: string
}

type SourcePart = {
  readonly id: string
  readonly data: string
}

type MigratedSession = {
  readonly summary_diffs: string | null
  readonly cost: number
  readonly tokens_input: number
  readonly tokens_output: number
  readonly tokens_reasoning: number
  readonly tokens_cache_read: number
  readonly tokens_cache_write: number
}

type MigratedMessage = {
  readonly id: string
  readonly type: string
  readonly seq: number
  readonly data: string
}

const fixtureSql = path.join(import.meta.dir, "fixtures", "v1-writer", "kilo.db.sql")
const cleanups: string[] = []

test("copies and migrates the checked-in fixture generated by the real Kilo-main V1 writer", async () => {
  if (!existsSync(fixtureSql)) throw new Error(`Missing generated V1 writer fixture: ${fixtureSql}`)

  const root = await mkdtemp(path.join(os.tmpdir(), "kilo2-v1-writer-dump-"))
  cleanups.push(root)
  const sourceDirectory = path.join(root, "source")
  const destinationDirectory = path.join(root, "destination")
  const source = path.join(sourceDirectory, "kilo.db")
  const destination = path.join(destinationDirectory, "kilo2.db")
  await Promise.all([sourceDirectory, destinationDirectory].map((directory) => mkdir(directory)))

  const sqlite = await import("bun:sqlite")
  {
    using db = new sqlite.Database(source, { create: true })
    db.exec(await Bun.file(fixtureSql).text())
  }

  const sourceInspection = await inspectV1Source(source)
  expect(sourceInspection.sessions).toBe(1)
  expect(sourceInspection.messages).toBe(4)
  expect(sourceInspection.parts).toBe(6)
  const beforeHashes = await contentHashes(source)

  let sessionID = ""
  {
    using db = new sqlite.Database(source, { readonly: true, strict: true })
    const session = db.query<SessionRow, []>("SELECT id, summary_diffs FROM session LIMIT 1").get()
    if (!session) throw new Error("Generated V1 fixture did not contain a session row")
    sessionID = session.id
    expect(JSON.parse(session.summary_diffs ?? "null")).toEqual([
      {
        file: "fixture.ts",
        patch: "@@ -0,0 +1 @@\n+fixture\n",
        before: "",
        after: "fixture\n",
        additions: 1,
        deletions: 0,
        status: "modified",
      },
    ])

    const messages = db
      .query<SourceMessage, [string]>("SELECT id, data FROM message WHERE session_id = ? ORDER BY time_created, id")
      .all(sessionID)
    expect(messages.map((message) => message.id)).toEqual([
      "msg_fixture_user",
      "msg_fixture_assistant",
      "msg_fixture_compaction",
      "msg_fixture_summary",
    ])
    expect(JSON.parse(messages[0].data)).toMatchObject({
      role: "user",
      editorContext: { activeFile: "fixture.ts", shell: "zsh" },
      summary: { diffs: [{ additions: 1, deletions: 0 }] },
    })
    expect(JSON.parse(messages[1].data)).toMatchObject({
      role: "assistant",
      structured: { fixture: true },
      variant: "fixture-variant",
      finish: "end_turn",
    })

    const parts = db.query<SourcePart, [string]>("SELECT id, data FROM part WHERE session_id = ?").all(sessionID)
    const partByID = new Map(parts.map((part) => [part.id, part]))
    expect(JSON.parse(partByID.get("prt_fixture_tool")?.data ?? "null")).toMatchObject({
      type: "tool",
      tool: "bash",
      state: { status: "completed", output: "fixture\n", input: { command: "printf fixture" } },
    })
    expect(JSON.parse(partByID.get("prt_fixture_step_finish")?.data ?? "null")).toMatchObject({
      type: "step-finish",
      generationID: "generation_fixture",
      vercelID: "vercel_fixture",
      metrics: { prompt: 101, generation: 202, source: "provider" },
    })
  }

  const copied = await copyV1Store({ source, destination })
  expect(copied.source.sha256).toBe(beforeHashes[0].sha256)
  expect(copied.source.sessions).toBe(1)
  expect(copied.source.messages).toBe(4)
  expect(copied.source.parts).toBe(6)

  const globalRoot = path.join(root, "v2-global")
  const migration = await Effect.runPromise(
    Effect.scoped(
      V1Migration.run().pipe(
        Effect.provide(Database.layer({ path: destination })),
        Effect.provide(
          Global.layerWith({
            home: path.join(globalRoot, "home"),
            data: path.join(globalRoot, "data"),
            config: path.join(globalRoot, "config"),
            cache: path.join(globalRoot, "cache"),
            state: path.join(globalRoot, "state"),
            tmp: path.join(globalRoot, "tmp"),
            log: path.join(globalRoot, "log"),
            bin: path.join(globalRoot, "bin"),
            repos: path.join(globalRoot, "repos"),
          }),
        ),
      ),
    ),
  )
  expect(migration).toEqual({ status: "completed" })
  expect(await contentHashes(source)).toEqual(beforeHashes)

  {
    using db = new sqlite.Database(destination, { readonly: true, strict: true })
    const session = db
      .query<MigratedSession, [string]>(
        `SELECT summary_diffs, cost, tokens_input, tokens_output, tokens_reasoning,
                tokens_cache_read, tokens_cache_write FROM session_v2 WHERE id = ?`,
      )
      .get(sessionID)
    expect(session).toMatchObject({
      cost: 0.75,
      tokens_input: 3,
      tokens_output: 5,
      tokens_reasoning: 5,
      tokens_cache_read: 7,
      tokens_cache_write: 7,
    })
    expect(JSON.parse(session?.summary_diffs ?? "null")).toEqual([
      {
        file: "fixture.ts",
        patch: "@@ -0,0 +1 @@\n+fixture\n",
        before: "",
        after: "fixture\n",
        additions: 1,
        deletions: 0,
        status: "modified",
      },
    ])

    const messages = db
      .query<
        MigratedMessage,
        [string]
      >("SELECT id, type, seq, data FROM session_message WHERE session_id = ? ORDER BY seq")
      .all(sessionID)
    expect(messages.map((message) => message.id)).toEqual([
      "msg_fixture_user",
      "msg_fixture_assistant",
      "msg_fixture_compaction",
    ])
    expect(messages.map((message) => message.type)).toEqual(["user", "assistant", "compaction"])
    expect(messages.map((message) => message.seq)).toEqual([0, 1, 2])

    const user = JSON.parse(messages[0].data) as Record<string, unknown>
    expect(user).toMatchObject({ text: "hello from the actual V1 writer", time: { created: 10 } })
    expect(user).not.toHaveProperty("editorContext")
    expect(user).not.toHaveProperty("summary")

    const assistant = JSON.parse(messages[1].data) as Record<string, unknown>
    expect(assistant).toMatchObject({
      model: { providerID: "fixture-provider", id: "fixture-model", variant: "fixture-variant" },
      finish: "unknown",
      tokens: { input: 2, output: 3, reasoning: 4, cache: { read: 5, write: 6 } },
    })
    expect(assistant).not.toHaveProperty("structured")
    const content = assistant.content as Array<Record<string, unknown>>
    expect(content).toContainEqual({ type: "text", text: "assistant response from the actual V1 writer" })
    expect(content.find((item) => item.type === "tool")).toMatchObject({
      id: "call_fixture",
      name: "bash",
      state: {
        status: "completed",
        input: { command: "printf fixture", description: "fixture command" },
        content: [{ type: "text", text: "fixture\n" }],
      },
    })

    const compaction = JSON.parse(messages[2].data) as Record<string, unknown>
    expect(compaction).toMatchObject({
      status: "completed",
      reason: "auto",
      summary: "compaction summary from the actual V1 writer",
    })
    expect(compaction.recent).toContain("hello from the actual V1 writer")
    expect(db.query("SELECT COUNT(*) AS count FROM event").get()).toEqual({ count: 0 })
  }
}, 120_000)

afterEach(async () => {
  while (cleanups.length > 0) await rm(cleanups.pop()!, { recursive: true, force: true })
})

async function contentHashes(filename: string) {
  return Promise.all(
    [filename, `${filename}-wal`].map(async (candidate) => ({
      path: candidate,
      sha256: await digest(candidate),
    })),
  )
}

async function digest(filename: string) {
  if (!existsSync(filename)) return ""
  const hasher = new Bun.CryptoHasher("sha256")
  for await (const chunk of createReadStream(filename)) hasher.update(chunk)
  return hasher.digest("hex")
}
