import { Cause, Effect } from "effect"
import type { MessageV2 } from "@/session/message-v2"
import type { SessionID } from "@/session/schema"
import type { Session } from "@/session/session"
import type { Snapshot } from "@/snapshot"

export namespace KiloSessionRevert {
  const rollback = <E>(snap: Snapshot.Interface, hash: string, files: string[], cause: Cause.Cause<E>) =>
    restore(snap, hash, files).pipe(
      Effect.matchCauseEffect({
        onFailure: (next) => Effect.failCause(Cause.combine(cause, next)),
        onSuccess: () => Effect.failCause(cause),
      }),
    )

  export function files(messages: MessageV2.WithParts[], rev: NonNullable<Session.Info["revert"]>) {
    const result: string[] = []
    let active = false
    for (const msg of messages) {
      for (const part of msg.parts) {
        if (active && part.type === "patch") result.push(...part.files)
        if (active || msg.info.id !== rev.messageID) continue
        if (rev.partID && part.id !== rev.partID) continue
        active = true
      }
    }
    return [...new Set(result)]
  }

  /**
   * Patch parts recorded by descendant sessions at or after the revert point.
   *
   * A delegated task runs in its own session with its own processor, so its edits land in patch
   * parts there. A child that keeps working after the parent's step window closed — a background
   * or goal-driven task, or one running in another worktree — is invisible to the parent's own
   * messages, and reverting the parent would leave its files behind.
   *
   * The revert point is matched by message time: message ids are generated by several code paths
   * and are not a reliable chronological order, which is why `SessionRevert` resolves its own
   * boundaries by position instead of by id.
   */
  export const descendants = Effect.fn("KiloSessionRevert.descendants")(function* (
    sessions: Pick<Session.Interface, "children" | "messages">,
    sessionID: SessionID,
    since: number,
  ) {
    const walk = (parent: SessionID): Effect.Effect<{ patches: Snapshot.Patch[]; files: string[] }> =>
      Effect.gen(function* () {
        const patches: Snapshot.Patch[] = []
        const files: string[] = []
        for (const kid of yield* sessions.children(parent).pipe(Effect.orDie)) {
          const nested = yield* walk(kid.id)
          patches.push(...nested.patches)
          files.push(...nested.files)
          for (const msg of yield* sessions.messages({ sessionID: kid.id }).pipe(Effect.orDie)) {
            if (msg.info.time.created < since) continue
            for (const part of msg.parts) {
              if (part.type !== "patch") continue
              patches.push(part)
              files.push(...part.files)
            }
          }
        }
        return { patches, files }
      })
    const found = yield* walk(sessionID)
    return { patches: found.patches, files: [...new Set(found.files)] }
  })

  export const apply = Effect.fn("KiloSessionRevert.apply")(function* <A, E, R>(
    snap: Snapshot.Interface,
    baseline: string | undefined,
    files: string[],
    effect: Effect.Effect<A, E, R>,
  ) {
    return yield* effect.pipe(
      Effect.catchCause((cause) => {
        if (!baseline || files.length === 0) return Effect.failCause(cause)
        return rollback(snap, baseline, files, cause)
      }),
    )
  })

  export const restore = Effect.fn("KiloSessionRevert.restore")(function* (
    snap: Snapshot.Interface,
    hash: string,
    files: string[],
  ) {
    if (files.length === 0) return
    yield* snap.revert([{ hash, files }])
  })
}
