packages:
  - src
  - webview-ui
  - apps/*
  - packages/*
  - storybook

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@vscode/vsce-sign'
  - core-js
  - esbuild
  - keytar
  - puppeteer-chromium-resolver
