packages:
  - src
  - webview-ui
  - apps/kilocode-docs
  - apps/playwright-e2e
  - apps/storybook
  - apps/vscode-e2e
  - apps/vscode-nightly
  - apps/web-evals
  - apps/web-roo-code
  - packages/*
  - jetbrains/host
  - jetbrains/plugin

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@vscode/vsce-sign'
  - core-js
  - esbuild
  - keytar
  - puppeteer-chromium-resolver
