import type { DaemonConfig } from "../types"

export type DaemonRequest = {
  id: string
  verb: string
  args: string[]
  directory?: string
  paths?: string[]
  config?: DaemonConfig
  /**
   * Per-daemon auth token (32-byte hex, 64 chars). Required on every request.
   * Generated by the daemon at startup and written to the handshake file
   * alongside `url`. Without a valid token the daemon rejects the request —
   * prevents any other local process on a multi-user system (or any other
   * process running as your user) from driving the browser by POSTing to
   * the daemon's HTTP endpoint.
   */
  auth?: string
}

export type DaemonResponse = {
  id: string
  ok: boolean
  envelope: Record<string, unknown>
  message?: string
}

export type DaemonLifecycleResponse = {
  id: string
  ok: boolean
  message?: string
}

export type DaemonHandshake = {
  pid: number
  version: string
  startedAt: number
  idleTimeoutMs: number
  sessionID: string
  /**
   * Base URL of the per-session HTTP endpoint, e.g. `http://127.0.0.1:54321`.
   * Single source of truth — clients POST to `${url}/call` and need not
   * reconstruct host/port themselves.
   */
  url: string
  /**
   * Per-daemon auth token. Clients must echo this on every request.
   * See `DaemonRequest.auth`.
   */
  token: string
}

function record(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value)
}

export function isHandshake(value: unknown): value is DaemonHandshake {
  if (!record(value)) return false
  return (
    typeof value.pid === "number" &&
    typeof value.version === "string" &&
    typeof value.startedAt === "number" &&
    typeof value.idleTimeoutMs === "number" &&
    typeof value.sessionID === "string" &&
    typeof value.url === "string" &&
    typeof value.token === "string"
  )
}

export function isRequest(value: unknown): value is DaemonRequest {
  if (!record(value)) return false
  if (typeof value.id !== "string" || typeof value.verb !== "string") return false
  if (!Array.isArray(value.args) || !value.args.every((arg) => typeof arg === "string")) return false
  if (value.directory !== undefined && typeof value.directory !== "string") return false
  if (
    value.paths !== undefined &&
    (!Array.isArray(value.paths) || !value.paths.every((item) => typeof item === "string"))
  )
    return false
  if (value.auth !== undefined && typeof value.auth !== "string") return false
  return value.config === undefined || config(value.config)
}

function config(value: unknown): value is DaemonConfig {
  if (!record(value)) return false
  if (Object.keys(value).some((key) => key !== "browser")) return false
  if (value.browser === undefined) return true
  if (!record(value.browser)) return false
  const keys = ["headless", "antiDetect", "timeoutMs", "viewport", "executablePath", "useSystemChrome", "args"]
  if (Object.keys(value.browser).some((key) => !keys.includes(key))) return false
  if (value.browser.headless !== undefined && typeof value.browser.headless !== "boolean") return false
  if (value.browser.antiDetect !== undefined && typeof value.browser.antiDetect !== "boolean") return false
  if (value.browser.useSystemChrome !== undefined && typeof value.browser.useSystemChrome !== "boolean") return false
  if (value.browser.executablePath !== undefined && typeof value.browser.executablePath !== "string") return false
  if (
    value.browser.args !== undefined &&
    (!Array.isArray(value.browser.args) || !value.browser.args.every((item) => typeof item === "string"))
  )
    return false
  if (value.browser.timeoutMs !== undefined && typeof value.browser.timeoutMs !== "number") return false
  if (value.browser.viewport === undefined) return true
  if (!record(value.browser.viewport)) return false
  return typeof value.browser.viewport.width === "number" && typeof value.browser.viewport.height === "number"
}

export function isResponse(value: unknown): value is DaemonResponse {
  if (!record(value)) return false
  if (typeof value.id !== "string" || typeof value.ok !== "boolean" || !record(value.envelope)) return false
  return value.message === undefined || typeof value.message === "string"
}
