name: Bug Report
description: Report a broken behavior in plain language with minimal reproduction steps
labels: ["bug"]
title: "(BUG)"
body:
  - type: markdown
    attributes:
      value: |
        Search existing issues first, please and thank you.
        https://github.com/Kilo-Org/kilocode/issues

  - type: textarea
    id: problem
    attributes:
      label: Simple problem statement (a few sentences)
      description: Describe what went wrong in simple language.
      placeholder: Trying to read the file, and the Model went into a loop, until the repition trigger stopped it.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Who's affected and when
      description: Who sees this and in what situation? Keep it non-technical.
      placeholder: This happens when I try to edit the prompt in the Chat area
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce the behavior
      description: Number your steps, write clearly
      placeholder: |
        1) Environment/setup (OS, Kilo version, shell)
        2) IDE details Visual Studio Code or JetBrains IDE name (Rider, IntelliJ etc...)
        3) List actions exactly (clicks, text entered, Settings page)
        4) What did you observe after each step
        Screengrabs and short videos would be helpful for UI bugs
    validations:
      required: true

  - type: input
    id: expected
    attributes:
      label: What did you expect to happen?
      placeholder: The dropdown shows all the models
    validations:
      required: true

  - type: input
    id: actual
    attributes:
      label: What actually happened
      placeholder: The dropdown did not show any Anthropic models
    validations:
      required: true

  - type: textarea
    id: variations
    attributes:
      label: What variations did you try? (optional)
      description: Different IDE's, Insiders, EAP, devices, providers, or settings experimented with.
      placeholder: Tried this flow in PHPStorm, it works in there

  - type: input
    id: version
    attributes:
      label: App Version
      description: What version of kilocode are you using?
      placeholder: 4.96.1
    validations:
      required: true
      
  - type: dropdown
    id: jetbrainsIDE
    attributes:
      label: JetBrains IDE
      options:
         - Rider
         - IntelliJ
         - PyCharm
         - PHPStorm
         - RustRover
         - CLion
         - DataSpell
         - Webstorm
         - Fleet
         - DataGrip
         - RubyMine
         - GoLand
         - MPS
         
  - type: input
    id: jetbrains-version
    attributes:
      label: JetBrains Version
      description: What version of the Jetbrains IDE are you using?
      placeholder: 2025.2.0
    validations:
      required: true
      
  - type: dropdown
    id: jetbrainsChannel
    attributes:
      label: Jetbrains Channel
      options:
          - Release
          - EAP
          
  - type: dropdown
    id: provider
    attributes:
      label: Provider (optional)
      options:
        - Kilo Provider
        - Anthropic
        - AWS Bedrock
        - Chutes AI
        - DeepSeek
        - Featherless AI
        - Fireworks AI
        - Glama
        - Google Gemini
        - Google Vertex AI
        - Groq
        - Human Relay Provider
        - LiteLLM
        - LM Studio
        - Mistral AI
        - Ollama
        - OpenAI
        - OpenAI Compatible
        - OpenRouter
        - Requesty
        - SambaNova
        - Unbound
        - VS Code Language Model API
        - xAI (Grok)
        - Not Applicable / Other

  - type: input
    id: model
    attributes:
      label: Model Used (optional)
      description: Exact model name (e.g., GPT-5). Use N/A if it doesnt matter.

  - type: textarea
    id: task-dump
    attributes:
      label: Task Export
      description: Task
      placeholder: Put your Task Export here in needed
      render: xml
      
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or errors (optional)
      description: Paste relevant output or errors. Triple backticks (```) please for formatting.
      render: shell
      
  - type: textarea
    id: MCPs
    attributes:
      label: MCP Json Configuration (optional)
      description: Paste your MCP configurations, global and project json, if applicable. Remember to remove your keys and PAT tokens.
      render: json
