name: Bug Report
description: File a bug report
type: "Bug"
body:
    - type: textarea
      attributes:
          label: Description
          description: |
            Please specify the app version you're using (e.g. v3.3.1)
            Which API Provider are you using? (e.g. Kilo, OpenRouter, Anthropic)
            Which Model are you using? (e.g. Claude 3.7 Sonnet)
            Steps to reproduce?
            Relevant API REQUEST output?
            Additional context?
