openapi: 3.0.3
info:
  title: Kilo Code Enhanced Chat API
  description: API for enhanced chat functionality with source discovery and citations
  version: 1.0.0
  contact:
    name: Kilo Code Team
    email: support@kilo.ai

servers:
  - url: http://localhost:3000/api/v1
    description: Development server

paths:
  /chat/sessions:
    post:
      summary: Create a new chat session
      operationId: createChatSession
      tags:
        - Chat Sessions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateChatSessionRequest'
      responses:
        '201':
          description: Chat session created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatSession'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'

    get:
      summary: List chat sessions for user
      operationId: listChatSessions
      tags:
        - Chat Sessions
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
            maximum: 100
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: List of chat sessions
          content:
            application/json:
              schema:
                type: object
                properties:
                  sessions:
                    type: array
                    items:
                      $ref: '#/components/schemas/ChatSession'
                  total:
                    type: integer
                  hasMore:
                    type: boolean
        '500':
          $ref: '#/components/responses/InternalServerError'

  /chat/sessions/{sessionId}:
    get:
      summary: Get chat session by ID
      operationId: getChatSession
      tags:
        - Chat Sessions
      parameters:
        - name: sessionId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Chat session details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatSession'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

    delete:
      summary: Delete chat session
      operationId: deleteChatSession
      tags:
        - Chat Sessions
      parameters:
        - name: sessionId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Chat session deleted successfully
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /chat/sessions/{sessionId}/messages:
    post:
      summary: Send a message to chat session
      operationId: sendMessage
      tags:
        - Chat Messages
      parameters:
        - name: sessionId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendMessageRequest'
      responses:
        '201':
          description: Message sent and response received
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatMessageResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

    get:
      summary: Get messages in chat session
      operationId: getChatMessages
      tags:
        - Chat Messages
      parameters:
        - name: sessionId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: limit
          in: query
          schema:
            type: integer
            default: 50
            maximum: 200
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: List of chat messages
          content:
            application/json:
              schema:
                type: object
                properties:
                  messages:
                    type: array
                    items:
                      $ref: '#/components/schemas/ChatMessage'
                  total:
                    type: integer
                  hasMore:
                    type: boolean
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /chat/sessions/{sessionId}/context:
    get:
      summary: Get current context for chat session
      operationId: getChatContext
      tags:
        - Chat Context
      parameters:
        - name: sessionId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Current chat context
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompletionContext'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

    put:
      summary: Update context for chat session
      operationId: updateChatContext
      tags:
        - Chat Context
      parameters:
        - name: sessionId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateContextRequest'
      responses:
        '200':
          description: Context updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompletionContext'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    CreateChatSessionRequest:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          maxLength: 255
          description: Session title
        initialContext:
          $ref: '#/components/schemas/CompletionContext'
          description: Optional initial context

    ChatSession:
      type: object
      required:
        - id
        - userId
        - title
        - createdAt
        - updatedAt
      properties:
        id:
          type: string
          format: uuid
          description: Unique session identifier
        userId:
          type: string
          description: User who owns the session
        title:
          type: string
          maxLength: 255
          description: Session title
        createdAt:
          type: string
          format: date-time
          description: Session creation timestamp
        updatedAt:
          type: string
          format: date-time
          description: Last activity timestamp
        context:
          $ref: '#/components/schemas/CompletionContext'
          description: Current session context
        metadata:
          type: object
          description: Additional session metadata

    SendMessageRequest:
      type: object
      required:
        - content
        - role
      properties:
        content:
          type: string
          maxLength: 100000
          description: Message content
        role:
          type: string
          enum: [user, assistant]
          description: Message sender role
        context:
          $ref: '#/components/schemas/CompletionContext'
          description: Optional context override
        includeCitations:
          type: boolean
          default: true
          description: Whether to include source citations

    ChatMessage:
      type: object
      required:
        - id
        - sessionId
        - role
        - content
        - timestamp
      properties:
        id:
          type: string
          format: uuid
          description: Unique message identifier
        sessionId:
          type: string
          format: uuid
          description: Chat session ID
        role:
          type: string
          enum: [user, assistant]
          description: Message sender role
        content:
          type: string
          maxLength: 100000
          description: Message content
        timestamp:
          type: string
          format: date-time
          description: Message timestamp
        citations:
          type: array
          items:
            $ref: '#/components/schemas/Citation'
          description: Source citations for assistant messages
        metadata:
          type: object
          description: Additional message metadata

    ChatMessageResponse:
      type: object
      required:
        - message
        - responseTime
      properties:
        message:
          $ref: '#/components/schemas/ChatMessage'
          description: The response message
        responseTime:
          type: number
          description: Response time in milliseconds
        context:
          $ref: '#/components/schemas/CompletionContext'
          description: Updated context after message

    Citation:
      type: object
      required:
        - id
        - sourceType
        - sourcePath
        - snippet
        - confidence
      properties:
        id:
          type: string
          format: uuid
          description: Unique citation identifier
        sourceType:
          type: string
          enum: [file, documentation, url]
          description: Type of source
        sourcePath:
          type: string
          maxLength: 1000
          description: File path or URL
        startLine:
          type: integer
          minimum: 1
          description: Start line for file citations
        endLine:
          type: integer
          minimum: 1
          description: End line for file citations
        snippet:
          type: string
          maxLength: 1000
          description: Relevant code snippet
        confidence:
          type: number
          minimum: 0
          maximum: 1
          description: Relevance confidence score
        metadata:
          type: object
          description: Additional citation metadata

    CompletionContext:
      type: object
      required:
        - id
        - filePath
        - position
        - surroundingCode
        - projectContext
        - semanticContext
      properties:
        id:
          type: string
          format: uuid
          description: Unique context identifier
        sessionId:
          type: string
          format: uuid
          description: Optional chat session ID
        filePath:
          type: string
          description: Current file path
        position:
          type: integer
          minimum: 0
          description: Cursor position in file
        surroundingCode:
          type: string
          maxLength: 10000
          description: Code around cursor
        projectContext:
          $ref: '#/components/schemas/ProjectContext'
          description: Project-wide context
        semanticContext:
          $ref: '#/components/schemas/SemanticContext'
          description: Vector-based semantic context
        metadata:
          type: object
          description: Additional context metadata

    UpdateContextRequest:
      type: object
      required:
        - filePath
        - position
        - surroundingCode
      properties:
        filePath:
          type: string
          description: Current file path
        position:
          type: integer
          minimum: 0
          description: Cursor position in file
        surroundingCode:
          type: string
          maxLength: 10000
          description: Code around cursor
        projectContext:
          $ref: '#/components/schemas/ProjectContext'
          description: Project-wide context
        semanticContext:
          $ref: '#/components/schemas/SemanticContext'
          description: Vector-based semantic context

    ProjectContext:
      type: object
      required:
        - projectPath
        - language
        - dependencies
        - recentFiles
      properties:
        projectPath:
          type: string
          description: Root directory of project
        language:
          type: string
          description: Primary programming language
        framework:
          type: string
          description: Framework being used
        dependencies:
          type: array
          items:
            type: string
          maxItems: 1000
          description: Project dependencies
        recentFiles:
          type: array
          items:
            type: string
          maxItems: 50
          description: Recently accessed files
        gitBranch:
          type: string
          description: Current git branch
        metadata:
          type: object
          description: Additional project metadata

    SemanticContext:
      type: object
      required:
        - embeddings
        - relevantFiles
        - concepts
        - relationships
      properties:
        embeddings:
          type: array
          items:
            type: array
            items:
              type: number
          description: Vector embeddings
        relevantFiles:
          type: array
          items:
            $ref: '#/components/schemas/FileReference'
          maxItems: 20
          description: Semantically similar files
        concepts:
          type: array
          items:
            type: string
          maxItems: 100
          description: Key concepts identified
        relationships:
          type: array
          items:
            $ref: '#/components/schemas/ConceptRelationship'
          maxItems: 200
          description: Concept relationships
        metadata:
          type: object
          description: Additional semantic metadata

    FileReference:
      type: object
      required:
        - id
        - filePath
        - changeType
      properties:
        id:
          type: string
          format: uuid
          description: Unique file reference identifier
        filePath:
          type: string
          description: Absolute file path
        changeType:
          type: string
          enum: [create, update, delete]
          description: Type of change
        oldContent:
          type: string
          description: Original content (for updates)
        newContent:
          type: string
          description: New content (for creates/updates)
        metadata:
          type: object
          description: Additional file metadata

    ConceptRelationship:
      type: object
      required:
        - concept1
        - concept2
        - relationshipType
        - strength
      properties:
        concept1:
          type: string
          description: First concept
        concept2:
          type: string
          description: Second concept
        relationshipType:
          type: string
          enum: [related, depends_on, similar_to, opposite_of]
          description: Type of relationship
        strength:
          type: number
          minimum: 0
          maximum: 1
          description: Relationship strength

    ErrorResponse:
      type: object
      required:
        - error
        - message
        - timestamp
      properties:
        error:
          type: string
          description: Error code
        message:
          type: string
          description: Human-readable error message
        timestamp:
          type: string
          format: date-time
          description: Error timestamp
        details:
          type: object
          description: Additional error details

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: []
