id = "kilo"
name = "Kilo"
description = "The open source coding agent."
<<<<<<< HEAD
version = "1.14.29"
=======
version = "7.2.31"
>>>>>>> origin/main
schema_version = 1
authors = ["Anomaly"]
repository = "https://github.com/Kilo-Org/kilocode"

[agent_servers.opencode]
name = "Kilo"
icon = "./icons/opencode.svg"

[agent_servers.opencode.targets.darwin-aarch64]
<<<<<<< HEAD
archive = "https://github.com/Kilo-Org/kilocode/releases/download/v1.14.29/opencode-darwin-arm64.zip"
=======
archive = "https://github.com/Kilo-Org/kilocode/releases/download/v7.2.31/opencode-darwin-arm64.zip"
>>>>>>> origin/main
cmd = "./opencode"
args = ["acp"]

[agent_servers.opencode.targets.darwin-x86_64]
<<<<<<< HEAD
archive = "https://github.com/Kilo-Org/kilocode/releases/download/v1.14.29/opencode-darwin-x64.zip"
=======
archive = "https://github.com/Kilo-Org/kilocode/releases/download/v7.2.31/opencode-darwin-x64.zip"
>>>>>>> origin/main
cmd = "./opencode"
args = ["acp"]

[agent_servers.opencode.targets.linux-aarch64]
<<<<<<< HEAD
archive = "https://github.com/Kilo-Org/kilocode/releases/download/v1.14.29/opencode-linux-arm64.tar.gz"
=======
archive = "https://github.com/Kilo-Org/kilocode/releases/download/v7.2.31/opencode-linux-arm64.tar.gz"
>>>>>>> origin/main
cmd = "./opencode"
args = ["acp"]

[agent_servers.opencode.targets.linux-x86_64]
<<<<<<< HEAD
archive = "https://github.com/Kilo-Org/kilocode/releases/download/v1.14.29/opencode-linux-x64.tar.gz"
=======
archive = "https://github.com/Kilo-Org/kilocode/releases/download/v7.2.31/opencode-linux-x64.tar.gz"
>>>>>>> origin/main
cmd = "./opencode"
args = ["acp"]

[agent_servers.opencode.targets.windows-x86_64]
<<<<<<< HEAD
archive = "https://github.com/Kilo-Org/kilocode/releases/download/v1.14.29/opencode-windows-x64.zip"
=======
archive = "https://github.com/Kilo-Org/kilocode/releases/download/v7.2.31/opencode-windows-x64.zip"
>>>>>>> origin/main
cmd = "./opencode.exe"
args = ["acp"]
