# kilocode_change - new file
name: "Setup Kilo"
description: "Install Kilo CLI globally"
runs:
  using: "composite"
  steps:
    - name: Install Kilo CLI
      run: curl -fsSL https://kilo.ai/cli/install | bash
      shell: bash

    - name: Add Kilo to PATH
      run: echo "$HOME/.kilo/bin" >> $GITHUB_PATH
      shell: bash

    - name: Create opencode compatibility shim
      run: |
        if [ -x "$HOME/.kilo/bin/kilo" ] && [ ! -x "$HOME/.kilo/bin/opencode" ]; then
          ln -sf "$HOME/.kilo/bin/kilo" "$HOME/.kilo/bin/opencode"
        fi
      shell: bash
