// Auto-generated from packages/kilo-console/src/routes/config/stack/technology-icons.ts
// Maps a Stack technology id to its Dashboard Icon asset (filename with extension)
// under packages/kilo-vscode/assets/icons/dashboard/. Keep in sync with kilo-console.
export const icons: Record<string, string> = {
  "apache-airflow": "apache-airflow.svg",
  dagster: "dagster-light.svg",
  "azure-data-factory": "azure-data-factory.svg",
  "aws-glue": "aws.svg",
  prefect: "prefect.png",
  dbt: "dbt.png",
  astronomer: "astronomer.png",
  "apache-spark": "apache.svg",
  stitch: "stitch.png",
  "apache-nifi": "apache.svg",
  fivetran: "fivetran.png",
  airbyte: "airbyte.png",
  matillion: "matillion.png",
  "azure-event-hub": "azure.svg",
  "aws-kinesis": "aws.svg",
  "gcp-pubsub": "google-cloud.svg",
  "spark-streaming": "apache.svg",
  "apache-kafka": "kafka.svg",
  "apache-flink": "apache.svg",
  "apache-beam": "apache.svg",
  databricks: "databricks.svg",
  snowflake: "snowflake.png",
  "azure-synapse": "azure.svg",
  "aws-redshift": "aws.svg",
  "gcp-bigquery": "google-cloud.svg",
  "azure-adls2": "azure-storage-accounts.svg",
  "aws-s3": "aws.svg",
  "gcp-storage": "google-cloud.svg",
  hdfs: "apache.svg",
  "oracle-cloud-storage": "oracle-cloud.svg",
  "apache-parquet": "apache.svg",
  "databricks-delta": "databricks.svg",
  "apache-iceberg": "apache-iceberg.svg",
  "apache-orc": "apache.svg",
  "apache-avro": "apache.svg",
  json: "json.svg",
  "apache-hudi": "apache.svg",
  "apache-arrow": "apache.svg",
  csv: "files.svg",
  xml: "w3c.svg",
  "microsoft-sql-server": "microsoft-sql-server-light.svg",
  mysql: "mysql.svg",
  oracle: "oracle.svg",
  "apache-hbase": "apache.svg",
  postgresql: "postgresql.svg",
  cassandra: "apache-cassandra.svg",
  mongodb: "mongodb.svg",
  elasticsearch: "elasticsearch.svg",
  redis: "redis.svg",
  "ibm-db2": "ibm.svg",
  tableau: "salesforce.svg",
  "power-bi": "powerbi.svg",
  "qlik-sense": "qlik.svg",
  "google-looker": "looker.svg",
  graphql: "graphql.png",
  fastapi: "fastapi.svg",
  "azure-data-share": "azure.svg",
  "aws-data-exchange": "aws.svg",
  "delta-sharing": "databricks.svg",
  "snowflake-data-sharing": "snowflake.png",
  "aws-sagemaker": "aws.svg",
  "gcp-vertex-ai": "google-cloud.svg",
  "azure-ml": "azure.svg",
  "databricks-ml": "databricks.svg",
  tensorflow: "tensorflow.svg",
  pytorch: "pytorch.svg",
  "h2o-ai": "h2o-ai.png",
  mlflow: "ml-flow-wordmark.svg",
  "scikit-learn": "python.svg",
  datarobot: "datarobot.png",
  "azure-ad": "microsoft.svg",
  "aws-cognito": "aws.svg",
  "gcp-identity": "google-cloud.svg",
  okta: "okta.svg",
  cyberark: "cyberark.png",
  collibra: "collibra.png",
  "apache-atlas": "apache.svg",
  "azure-purview": "microsoft.svg",
  "aws-glue-data-catalog": "aws.svg",
  "gcp-bigquery-dg": "google-cloud.svg",
  privacera: "privacera.png",
  "unity-catalog": "databricks.svg",
  "hive-metastore": "apache.svg",
  dremio: "dremio.png",
  prometheus: "prometheus.svg",
  grafana: "grafana.svg",
  splunk: "splunk.svg",
  "new-relic": "new-relic.png",
  datadog: "datadog.svg",
  "azure-key-vault": "azure-keyvault.svg",
  "aws-secrets-manager": "aws.svg",
  "gcp-secret-manager": "google-cloud.svg",
  "hashicorp-vault": "hashicorp-vault.svg",
  "cyberark-conjur": "cyberark.png",
  "great-expectations": "great-expectations.png",
  "dbt-data-tests": "dbt.png",
  openmetadata: "openmetadata.png",
  "soda-core-cl": "soda.png",
  "azure-purview-dq": "microsoft.svg",
  "aws-glue-dq": "aws.svg",
}

const FALLBACK = "code.svg"

export function dashboardIcon(id: string): string {
  return icons[id] ?? FALLBACK
}
