// kilocode_change - new file

/**
 * Commits the agent's packages/kilo-docs changes, pushes the rolling branch,
 * and creates or updates the rolling auto-docs PR.
 *
 * No-op when the agent produced no docs changes. PRs become drafts when the
 * diff exceeds the file cap or verification failed. The PR body carries
 * marker-delimited sections so later runs can append rows, plus a
 * machine-readable processed-through watermark.
 */

import { execFileSync } from "node:child_process"
import fs from "node:fs"
import { pathToFileURL } from "node:url"

const BRANCH = process.env.BRANCH || "docs/auto-sync"
const FILE_CAP = 15
const ROW_CAP = 150
const SUMMARY_FILE = ".docs-sync-summary.json"
const DOCS_PATH = "packages/kilo-docs"

const git = (args) => execFileSync("git", args, { stdio: ["ignore", "pipe", "inherit"] }).toString().trim()

function shortRef(url) {
  return String(url).replace("https://github.com/", "").replace("/pull/", "#")
}

function changeRow(e) {
  return `| ${e.action} | [${shortRef(e.url)}](${e.url}) |`
}

function skippedRow(e) {
  const reason = String(e.reason ?? "").replaceAll("|", "\\|").replaceAll("\n", " ")
  return `| [${shortRef(e.url)}](${e.url}) | ${reason} |`
}

export function extractSectionRows(body, name) {
  const m = String(body ?? "").match(
    new RegExp(`<!--\\s*docs-sync:${name}:start\\s*-->([\\s\\S]*?)<!--\\s*docs-sync:${name}:end\\s*-->`),
  )
  if (!m) return []
  return m[1]
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l.startsWith("|") && !l.startsWith("| ---") && !/^\|\s*Docs change/.test(l) && !/^\|\s*PR\s*\|/.test(l))
}

function section(name, header, rows) {
  const body = rows.length > 0 ? [header, "| --- | --- |", ...rows].join("\n") : "_None._"
  return `<!-- docs-sync:${name}:start -->\n${body}\n<!-- docs-sync:${name}:end -->`
}

export function renderBody({ date, since, through, changesRows, skippedRows, verified, draftReasons }) {
  return `## Automated docs sync — ${date}

This PR keeps kilo.ai/docs in sync with features merged to [Kilo-Org/cloud](https://github.com/Kilo-Org/cloud) and [Kilo-Org/kilocode](https://github.com/Kilo-Org/kilocode). Every change below links to the merged PR it documents.

- Window: \`${since}\` → \`${through}\`
- Verification (docs build + tests): **${verified ? "passing" : "FAILING — needs a human look"}**
${draftReasons.length > 0 ? `- Draft because: ${draftReasons.join("; ")}\n` : ""}
### Changes

${section("changes", "| Docs change | Source |", changesRows)}

### Considered, no docs change needed

${section("skipped", "| PR | Reason |", skippedRows)}

---

(bot) Generated by the docs-sync workflow. Humans review and merge; while this PR stays open, the next daily run appends new changes here. Branch: \`${BRANCH}\`.
<!-- docs-sync: processed-through ${through} -->
`
}

function mergeRows(oldRows, newRows) {
  const seen = new Set()
  const out = []
  for (const row of [...oldRows, ...newRows]) {
    if (seen.has(row)) continue
    seen.add(row)
    out.push(row)
  }
  return out.slice(-ROW_CAP)
}

function readJson(path, fallback) {
  try {
    return JSON.parse(fs.readFileSync(path, "utf8"))
  } catch {
    return fallback
  }
}

async function main() {
  const { api, appendOutput, appendSummary, repo } = await import("./lib.mjs")

  const through = process.env.PROCESSED_THROUGH ?? new Date().toISOString()
  const since = process.env.SINCE ?? "unknown"
  const mode = process.env.PREP_MODE === "update" ? "update" : "fresh"
  const existingPr = process.env.PR_NUMBER || ""
  const verified = process.env.VERIFIED === "true"
  const date = through.slice(0, 10)

  // The agent's run summary is consumed here and never committed.
  const agentSummary = readJson(SUMMARY_FILE, [])
  fs.rmSync(SUMMARY_FILE, { force: true })
  const triage = readJson("docs-sync-out/triage.json", [])

  if (git(["status", "--porcelain", "--", DOCS_PATH]) === "") {
    console.log("no packages/kilo-docs changes produced; nothing to commit")
    appendSummary("### docs-sync: no docs changes\n\nThe agent found nothing worth documenting in this window.")
    return
  }

  git(["config", "user.name", "github-actions[bot]"])
  git(["config", "user.email", "41898282+github-actions[bot]@users.noreply.github.com"])
  git(["add", DOCS_PATH])
  const changedFiles = git(["diff", "--cached", "--name-only"]).split("\n").filter(Boolean)
  git(["commit", "-m", `docs: sync with merged PRs (${date})`])

  const draftReasons = []
  if (changedFiles.length > FILE_CAP) draftReasons.push(`diff exceeds ${FILE_CAP} files (${changedFiles.length})`)
  if (!verified) draftReasons.push("docs build/tests not passing")
  const draft = draftReasons.length > 0

  git(mode === "update" ? ["push", "origin", `HEAD:${BRANCH}`] : ["push", "--force-with-lease", "origin", `HEAD:${BRANCH}`])

  const changesNew = agentSummary.filter((e) => e.action !== "skipped").map(changeRow)
  const skippedNew = [
    ...triage.filter((e) => e.docs_worthy === false),
    ...agentSummary.filter((e) => e.action === "skipped"),
  ].map(skippedRow)

  let oldChanges = []
  let oldSkipped = []
  if (mode === "update" && existingPr) {
    const pr = await api(`/repos/${repo()}/pulls/${existingPr}`)
    oldChanges = extractSectionRows(pr.body, "changes")
    oldSkipped = extractSectionRows(pr.body, "skipped")
  }

  const body = renderBody({
    date,
    since,
    through,
    changesRows: mergeRows(oldChanges, changesNew),
    skippedRows: mergeRows(oldSkipped, skippedNew),
    verified,
    draftReasons,
  })

  try {
    await api(`/repos/${repo()}/labels`, {
      method: "POST",
      body: { name: "auto-docs", color: "1d76db", description: "Automated docs-sync PRs" },
    })
  } catch (err) {
    if (err.status !== 422) throw err // 422 = label already exists
  }

  let prNumber
  let prUrl
  if (mode === "update" && existingPr) {
    const pr = await api(`/repos/${repo()}/pulls/${existingPr}`, {
      method: "PATCH",
      body: { title: `docs: auto-sync with merged PRs (through ${date})`, body },
    })
    prNumber = pr.number
    prUrl = pr.html_url
    await api(`/repos/${repo()}/issues/${prNumber}/comments`, {
      method: "POST",
      body: {
        body: `(bot) Appended changes processed through \`${through}\`. Verification: **${verified ? "passing" : "failing"}**.${draft ? ` Draft because: ${draftReasons.join("; ")}.` : ""}`,
      },
    })
  } else {
    const pr = await api(`/repos/${repo()}/pulls`, {
      method: "POST",
      body: {
        title: `docs: auto-sync with merged PRs (through ${date})`,
        head: BRANCH,
        base: "main",
        body,
        draft,
      },
    })
    prNumber = pr.number
    prUrl = pr.html_url
    await api(`/repos/${repo()}/issues/${prNumber}/labels`, { method: "POST", body: { labels: ["auto-docs"] } })
  }

  appendOutput("pr_url", prUrl)
  appendSummary(`### docs-sync PR\n\n- ${prUrl}\n- changed files: ${changedFiles.length}\n- draft: ${draft}\n`)
  console.log(`PR ${prNumber}: ${prUrl} (draft=${draft}, files=${changedFiles.length})`)
}

const isMain = process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href
if (isMain) {
  main().catch((err) => {
    console.error(err)
    process.exit(1)
  })
}
