export { CommandPalette } from "./command-palette"
export { FooterBar } from "./footer-bar"
export { HelpOverlay } from "./help-overlay"
export { PasteModal } from "./paste-modal"
export { StageCoverageIndicator } from "./stage-coverage-indicator"
export type { StageCoverageIndicatorProps } from "./stage-coverage-indicator"
// Phase 5: density-toggle, stage-position-badge, detail-panel, tab-group
export { DensityToggle } from "./density-toggle"
export type { DensityToggleProps } from "./density-toggle"
export { StagePositionBadge } from "./stage-position-badge"
export type { StagePositionBadgeProps } from "./stage-position-badge"
export { DetailPanel } from "./detail-panel"
export type { DetailPanelProps } from "./detail-panel"
export { TabGroup } from "./tab-group"
export type { TabGroupProps, TabDescriptor, TabGroupChildrenRender } from "./tab-group"
export { OnboardingWizard } from "./onboarding-wizard"
export type { OnboardingWizardProps, OnboardingWizardStep, QuickstartEntry } from "./onboarding-wizard"
