import z from "zod"
import { TeamConfig } from "./config"

export const TeamPreset = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string(),
  icon: z.string().optional(),
  team: TeamConfig,
})

export type TeamPreset = z.infer<typeof TeamPreset>

export const TEAM_PRESETS: TeamPreset[] = [
  {
    id: "solo-enhanced",
    name: "Solo Enhanced",
    description: "Single lead agent with a fast research helper.",
    icon: "sparkles",
    team: {
      enabled: true,
      roles: {
        lead: {
          displayName: "Lead Engineer",
          provider: "kilo",
          model: "gpt-5",
          effort: "high",
          tier: 1,
          canDelegate: ["research"],
          maxConcurrent: 3,
          capabilities: ["implementation", "planning"],
        },
        research: {
          displayName: "Research Scout",
          provider: "kilo",
          model: "gpt-5-mini",
          effort: "low",
          tier: 2,
          canDelegate: [],
          maxConcurrent: 4,
          capabilities: ["lookup", "summaries"],
        },
      },
      routing: { strategy: "hierarchical", defaultRole: "lead", escalationEnabled: true },
      reactions: [],
    },
  },
  {
    id: "code-review-pair",
    name: "Code Review Pair",
    description: "Coder + reviewer for feature delivery with built-in quality checks.",
    icon: "shield-check",
    team: {
      enabled: true,
      roles: {
        coder: {
          displayName: "Coder",
          provider: "kilo",
          model: "gpt-5",
          effort: "high",
          tier: 1,
          canDelegate: ["reviewer"],
          maxConcurrent: 3,
          capabilities: ["implementation", "tests"],
        },
        reviewer: {
          displayName: "Reviewer",
          provider: "kilo",
          model: "claude-4.1-sonnet",
          effort: "medium",
          tier: 2,
          canDelegate: [],
          maxConcurrent: 2,
          capabilities: ["review", "risk-analysis"],
        },
      },
      routing: { strategy: "hierarchical", defaultRole: "coder", escalationEnabled: true },
      reactions: [],
    },
  },
  {
    id: "full-stack-team",
    name: "Full Stack Team",
    description: "Architect delegating to frontend, backend, and reviewer specialists.",
    icon: "layers",
    team: {
      enabled: true,
      roles: {
        architect: {
          displayName: "Architect",
          provider: "kilo",
          model: "gpt-5",
          effort: "high",
          tier: 1,
          canDelegate: ["frontend-dev", "backend-dev", "reviewer"],
          maxConcurrent: 4,
          capabilities: ["design", "coordination"],
        },
        "frontend-dev": {
          displayName: "Frontend Developer",
          provider: "kilo",
          model: "claude-4.1-sonnet",
          effort: "medium",
          tier: 2,
          canDelegate: ["reviewer"],
          maxConcurrent: 3,
          capabilities: ["ui", "accessibility"],
        },
        "backend-dev": {
          displayName: "Backend Developer",
          provider: "kilo",
          model: "gpt-5-mini",
          effort: "medium",
          tier: 2,
          canDelegate: ["reviewer"],
          maxConcurrent: 3,
          capabilities: ["api", "db"],
        },
        reviewer: {
          displayName: "Reviewer",
          provider: "kilo",
          model: "gpt-5-mini",
          effort: "low",
          tier: 2,
          canDelegate: [],
          maxConcurrent: 2,
          capabilities: ["code-review"],
        },
      },
      routing: { strategy: "hierarchical", defaultRole: "architect", escalationEnabled: true },
      reactions: [],
    },
  },
  {
    id: "ci-cd-pipeline",
    name: "CI/CD Pipeline",
    description: "Delivery-focused team with CI fix ownership and escalation.",
    icon: "branch",
    team: {
      enabled: true,
      roles: {
        release: {
          displayName: "Release Lead",
          provider: "kilo",
          model: "gpt-5",
          effort: "high",
          tier: 1,
          canDelegate: ["implementer", "ci-fixer"],
          maxConcurrent: 3,
          capabilities: ["release", "triage"],
        },
        implementer: {
          displayName: "Implementer",
          provider: "kilo",
          model: "claude-4.1-sonnet",
          effort: "medium",
          tier: 2,
          canDelegate: ["ci-fixer"],
          maxConcurrent: 4,
          capabilities: ["coding"],
        },
        "ci-fixer": {
          displayName: "CI Fixer",
          provider: "kilo",
          model: "gpt-5-mini",
          effort: "medium",
          tier: 2,
          canDelegate: [],
          maxConcurrent: 5,
          capabilities: ["ci", "tests"],
        },
      },
      routing: { strategy: "hierarchical", defaultRole: "release", escalationEnabled: true },
      reactions: [
        { trigger: "ci-failed", auto: true, action: "send-to-agent", targetRole: "ci-fixer", retries: 2 },
        { trigger: "agent-stuck", auto: true, action: "escalate", targetRole: "release", retries: 0, escalateAfterMinutes: 15 },
      ],
    },
  },
  {
    id: "research-team",
    name: "Research Team",
    description: "Research-first team for architecture and discovery work.",
    icon: "search",
    team: {
      enabled: true,
      roles: {
        orchestrator: {
          displayName: "Research Orchestrator",
          provider: "kilo",
          model: "gpt-5",
          effort: "high",
          tier: 1,
          canDelegate: ["deep-researcher", "fast-scanner"],
          maxConcurrent: 4,
          capabilities: ["synthesis"],
        },
        "deep-researcher": {
          displayName: "Deep Researcher",
          provider: "kilo",
          model: "claude-4.1-sonnet",
          effort: "high",
          tier: 2,
          canDelegate: [],
          maxConcurrent: 2,
          capabilities: ["analysis", "long-form"],
        },
        "fast-scanner": {
          displayName: "Fast Scanner",
          provider: "kilo",
          model: "gpt-5-mini",
          effort: "low",
          tier: 2,
          canDelegate: [],
          maxConcurrent: 6,
          capabilities: ["search", "triage"],
        },
      },
      routing: { strategy: "flat", defaultRole: "orchestrator", escalationEnabled: true },
      reactions: [],
    },
  },
]
